# Generated by Django 3.0.6 on 2020-05-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('in_django_site', '0004_auto_20200515_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='groupcomment',
            name='likes',
        ),
    ]
