# Generated by Django 3.0.6 on 2020-05-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_django_site', '0005_auto_20200515_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
