# Generated by Django 3.0.6 on 2020-05-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_django_site', '0006_story_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indjangouser',
            name='avatar',
            field=models.FileField(blank=True, default='avatars/anon.png', upload_to='avatars/'),
        ),
    ]
